import '../styles/modern-normalize.css';
import '../styles/style.css';
import '../styles/header.css';
import '../styles/hero.css';
import '../styles/about.css';
import '../styles/projects.css';
import '../styles/contact.css';
import '../styles/footer.css';
import '../styles/utils.css';